/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/_patient'
import { Route as DoctorRouteImport } from './routes/_doctor'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiVapiCallRouteImport } from './routes/api/vapi-call'
import { Route as ApiMedAnalysisRouteImport } from './routes/api/med-analysis'
import { Route as ApiDrugInteractionRouteImport } from './routes/api/drug-interaction'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeReportRouteImport } from './routes/api/analyze-report'
import { Route as PatientShareRouteImport } from './routes/_patient.share'
import { Route as PatientReportsRouteImport } from './routes/_patient.reports'
import { Route as PatientProfileRouteImport } from './routes/_patient.profile'
import { Route as PatientDrugSafetyRouteImport } from './routes/_patient.drug-safety'
import { Route as PatientDashboardRouteImport } from './routes/_patient.dashboard'
import { Route as PatientCarePlanRouteImport } from './routes/_patient.care-plan'
import { Route as PatientAppointmentsRouteImport } from './routes/_patient.appointments'
import { Route as PatientAaraRouteImport } from './routes/_patient.aara'
import { Route as DoctorDoctorRouteImport } from './routes/_doctor.doctor'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiQrShareViewRouteImport } from './routes/api/qr-share/view'
import { Route as ApiQrShareRevokeRouteImport } from './routes/api/qr-share/revoke'
import { Route as ApiQrShareCreateRouteImport } from './routes/api/qr-share/create'
import { Route as ApiNutritionSearchRouteImport } from './routes/api/nutrition/search'
import { Route as ApiNutritionGeneratePlanRouteImport } from './routes/api/nutrition/generate-plan'
import { Route as DoctorDoctorScanQrRouteImport } from './routes/_doctor.doctor.scan-qr'
import { Route as DoctorDoctorProfileRouteImport } from './routes/_doctor.doctor.profile'
import { Route as DoctorDoctorAppointmentsRouteImport } from './routes/_doctor.doctor.appointments'
import { Route as AdminAdminPatientsRouteImport } from './routes/_admin.admin.patients'
import { Route as AdminAdminDoctorsRouteImport } from './routes/_admin.admin.doctors'
import { Route as DoctorDoctorPatientIdRouteImport } from './routes/_doctor.doctor.patient.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/_patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallRoute = ApiVapiCallRouteImport.update({
  id: '/api/vapi-call',
  path: '/api/vapi-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedAnalysisRoute = ApiMedAnalysisRouteImport.update({
  id: '/api/med-analysis',
  path: '/api/med-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrugInteractionRoute = ApiDrugInteractionRouteImport.update({
  id: '/api/drug-interaction',
  path: '/api/drug-interaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeReportRoute = ApiAnalyzeReportRouteImport.update({
  id: '/api/analyze-report',
  path: '/api/analyze-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientShareRoute = PatientShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDrugSafetyRoute = PatientDrugSafetyRouteImport.update({
  id: '/drug-safety',
  path: '/drug-safety',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PatientCarePlanRoute = PatientCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAaraRoute = PatientAaraRouteImport.update({
  id: '/aara',
  path: '/aara',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorDoctorRoute = DoctorDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiQrShareViewRoute = ApiQrShareViewRouteImport.update({
  id: '/api/qr-share/view',
  path: '/api/qr-share/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrShareRevokeRoute = ApiQrShareRevokeRouteImport.update({
  id: '/api/qr-share/revoke',
  path: '/api/qr-share/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQrShareCreateRoute = ApiQrShareCreateRouteImport.update({
  id: '/api/qr-share/create',
  path: '/api/qr-share/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionSearchRoute = ApiNutritionSearchRouteImport.update({
  id: '/api/nutrition/search',
  path: '/api/nutrition/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNutritionGeneratePlanRoute =
  ApiNutritionGeneratePlanRouteImport.update({
    id: '/api/nutrition/generate-plan',
    path: '/api/nutrition/generate-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoctorDoctorScanQrRoute = DoctorDoctorScanQrRouteImport.update({
  id: '/scan-qr',
  path: '/scan-qr',
  getParentRoute: () => DoctorDoctorRoute,
} as any)
const DoctorDoctorProfileRoute = DoctorDoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorDoctorRoute,
} as any)
const DoctorDoctorAppointmentsRoute =
  DoctorDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DoctorDoctorRoute,
  } as any)
const AdminAdminPatientsRoute = AdminAdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDoctorsRoute = AdminAdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorDoctorPatientIdRoute = DoctorDoctorPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => DoctorDoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/doctor': typeof DoctorDoctorRouteWithChildren
  '/aara': typeof PatientAaraRoute
  '/appointments': typeof PatientAppointmentsRoute
  '/care-plan': typeof PatientCarePlanRoute
  '/dashboard': typeof PatientDashboardRoute
  '/drug-safety': typeof PatientDrugSafetyRoute
  '/profile': typeof PatientProfileRoute
  '/reports': typeof PatientReportsRoute
  '/share': typeof PatientShareRoute
  '/api/analyze-report': typeof ApiAnalyzeReportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drug-interaction': typeof ApiDrugInteractionRoute
  '/api/med-analysis': typeof ApiMedAnalysisRoute
  '/api/vapi-call': typeof ApiVapiCallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/doctors': typeof AdminAdminDoctorsRoute
  '/admin/patients': typeof AdminAdminPatientsRoute
  '/doctor/appointments': typeof DoctorDoctorAppointmentsRoute
  '/doctor/profile': typeof DoctorDoctorProfileRoute
  '/doctor/scan-qr': typeof DoctorDoctorScanQrRoute
  '/api/nutrition/generate-plan': typeof ApiNutritionGeneratePlanRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/qr-share/create': typeof ApiQrShareCreateRoute
  '/api/qr-share/revoke': typeof ApiQrShareRevokeRoute
  '/api/qr-share/view': typeof ApiQrShareViewRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/doctor/patient/$id': typeof DoctorDoctorPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/doctor': typeof DoctorDoctorRouteWithChildren
  '/aara': typeof PatientAaraRoute
  '/appointments': typeof PatientAppointmentsRoute
  '/care-plan': typeof PatientCarePlanRoute
  '/dashboard': typeof PatientDashboardRoute
  '/drug-safety': typeof PatientDrugSafetyRoute
  '/profile': typeof PatientProfileRoute
  '/reports': typeof PatientReportsRoute
  '/share': typeof PatientShareRoute
  '/api/analyze-report': typeof ApiAnalyzeReportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drug-interaction': typeof ApiDrugInteractionRoute
  '/api/med-analysis': typeof ApiMedAnalysisRoute
  '/api/vapi-call': typeof ApiVapiCallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/admin/doctors': typeof AdminAdminDoctorsRoute
  '/admin/patients': typeof AdminAdminPatientsRoute
  '/doctor/appointments': typeof DoctorDoctorAppointmentsRoute
  '/doctor/profile': typeof DoctorDoctorProfileRoute
  '/doctor/scan-qr': typeof DoctorDoctorScanQrRoute
  '/api/nutrition/generate-plan': typeof ApiNutritionGeneratePlanRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/qr-share/create': typeof ApiQrShareCreateRoute
  '/api/qr-share/revoke': typeof ApiQrShareRevokeRoute
  '/api/qr-share/view': typeof ApiQrShareViewRoute
  '/admin': typeof AdminAdminIndexRoute
  '/doctor/patient/$id': typeof DoctorDoctorPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_doctor': typeof DoctorRouteWithChildren
  '/_patient': typeof PatientRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_doctor/doctor': typeof DoctorDoctorRouteWithChildren
  '/_patient/aara': typeof PatientAaraRoute
  '/_patient/appointments': typeof PatientAppointmentsRoute
  '/_patient/care-plan': typeof PatientCarePlanRoute
  '/_patient/dashboard': typeof PatientDashboardRoute
  '/_patient/drug-safety': typeof PatientDrugSafetyRoute
  '/_patient/profile': typeof PatientProfileRoute
  '/_patient/reports': typeof PatientReportsRoute
  '/_patient/share': typeof PatientShareRoute
  '/api/analyze-report': typeof ApiAnalyzeReportRoute
  '/api/chat': typeof ApiChatRoute
  '/api/drug-interaction': typeof ApiDrugInteractionRoute
  '/api/med-analysis': typeof ApiMedAnalysisRoute
  '/api/vapi-call': typeof ApiVapiCallRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/_admin/admin/doctors': typeof AdminAdminDoctorsRoute
  '/_admin/admin/patients': typeof AdminAdminPatientsRoute
  '/_doctor/doctor/appointments': typeof DoctorDoctorAppointmentsRoute
  '/_doctor/doctor/profile': typeof DoctorDoctorProfileRoute
  '/_doctor/doctor/scan-qr': typeof DoctorDoctorScanQrRoute
  '/api/nutrition/generate-plan': typeof ApiNutritionGeneratePlanRoute
  '/api/nutrition/search': typeof ApiNutritionSearchRoute
  '/api/qr-share/create': typeof ApiQrShareCreateRoute
  '/api/qr-share/revoke': typeof ApiQrShareRevokeRoute
  '/api/qr-share/view': typeof ApiQrShareViewRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_doctor/doctor/patient/$id': typeof DoctorDoctorPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/doctor'
    | '/aara'
    | '/appointments'
    | '/care-plan'
    | '/dashboard'
    | '/drug-safety'
    | '/profile'
    | '/reports'
    | '/share'
    | '/api/analyze-report'
    | '/api/chat'
    | '/api/drug-interaction'
    | '/api/med-analysis'
    | '/api/vapi-call'
    | '/auth/callback'
    | '/share/$token'
    | '/admin/doctors'
    | '/admin/patients'
    | '/doctor/appointments'
    | '/doctor/profile'
    | '/doctor/scan-qr'
    | '/api/nutrition/generate-plan'
    | '/api/nutrition/search'
    | '/api/qr-share/create'
    | '/api/qr-share/revoke'
    | '/api/qr-share/view'
    | '/admin/'
    | '/doctor/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/doctor'
    | '/aara'
    | '/appointments'
    | '/care-plan'
    | '/dashboard'
    | '/drug-safety'
    | '/profile'
    | '/reports'
    | '/share'
    | '/api/analyze-report'
    | '/api/chat'
    | '/api/drug-interaction'
    | '/api/med-analysis'
    | '/api/vapi-call'
    | '/auth/callback'
    | '/share/$token'
    | '/admin/doctors'
    | '/admin/patients'
    | '/doctor/appointments'
    | '/doctor/profile'
    | '/doctor/scan-qr'
    | '/api/nutrition/generate-plan'
    | '/api/nutrition/search'
    | '/api/qr-share/create'
    | '/api/qr-share/revoke'
    | '/api/qr-share/view'
    | '/admin'
    | '/doctor/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_doctor'
    | '/_patient'
    | '/login'
    | '/onboarding'
    | '/_doctor/doctor'
    | '/_patient/aara'
    | '/_patient/appointments'
    | '/_patient/care-plan'
    | '/_patient/dashboard'
    | '/_patient/drug-safety'
    | '/_patient/profile'
    | '/_patient/reports'
    | '/_patient/share'
    | '/api/analyze-report'
    | '/api/chat'
    | '/api/drug-interaction'
    | '/api/med-analysis'
    | '/api/vapi-call'
    | '/auth/callback'
    | '/share/$token'
    | '/_admin/admin/doctors'
    | '/_admin/admin/patients'
    | '/_doctor/doctor/appointments'
    | '/_doctor/doctor/profile'
    | '/_doctor/doctor/scan-qr'
    | '/api/nutrition/generate-plan'
    | '/api/nutrition/search'
    | '/api/qr-share/create'
    | '/api/qr-share/revoke'
    | '/api/qr-share/view'
    | '/_admin/admin/'
    | '/_doctor/doctor/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAnalyzeReportRoute: typeof ApiAnalyzeReportRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDrugInteractionRoute: typeof ApiDrugInteractionRoute
  ApiMedAnalysisRoute: typeof ApiMedAnalysisRoute
  ApiVapiCallRoute: typeof ApiVapiCallRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiNutritionGeneratePlanRoute: typeof ApiNutritionGeneratePlanRoute
  ApiNutritionSearchRoute: typeof ApiNutritionSearchRoute
  ApiQrShareCreateRoute: typeof ApiQrShareCreateRoute
  ApiQrShareRevokeRoute: typeof ApiQrShareRevokeRoute
  ApiQrShareViewRoute: typeof ApiQrShareViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_patient': {
      id: '/_patient'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi-call': {
      id: '/api/vapi-call'
      path: '/api/vapi-call'
      fullPath: '/api/vapi-call'
      preLoaderRoute: typeof ApiVapiCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/med-analysis': {
      id: '/api/med-analysis'
      path: '/api/med-analysis'
      fullPath: '/api/med-analysis'
      preLoaderRoute: typeof ApiMedAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drug-interaction': {
      id: '/api/drug-interaction'
      path: '/api/drug-interaction'
      fullPath: '/api/drug-interaction'
      preLoaderRoute: typeof ApiDrugInteractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-report': {
      id: '/api/analyze-report'
      path: '/api/analyze-report'
      fullPath: '/api/analyze-report'
      preLoaderRoute: typeof ApiAnalyzeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_patient/share': {
      id: '/_patient/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof PatientShareRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/reports': {
      id: '/_patient/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/profile': {
      id: '/_patient/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/drug-safety': {
      id: '/_patient/drug-safety'
      path: '/drug-safety'
      fullPath: '/drug-safety'
      preLoaderRoute: typeof PatientDrugSafetyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/dashboard': {
      id: '/_patient/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/care-plan': {
      id: '/_patient/care-plan'
      path: '/care-plan'
      fullPath: '/care-plan'
      preLoaderRoute: typeof PatientCarePlanRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/appointments': {
      id: '/_patient/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_patient/aara': {
      id: '/_patient/aara'
      path: '/aara'
      fullPath: '/aara'
      preLoaderRoute: typeof PatientAaraRouteImport
      parentRoute: typeof PatientRoute
    }
    '/_doctor/doctor': {
      id: '/_doctor/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorDoctorRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/qr-share/view': {
      id: '/api/qr-share/view'
      path: '/api/qr-share/view'
      fullPath: '/api/qr-share/view'
      preLoaderRoute: typeof ApiQrShareViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-share/revoke': {
      id: '/api/qr-share/revoke'
      path: '/api/qr-share/revoke'
      fullPath: '/api/qr-share/revoke'
      preLoaderRoute: typeof ApiQrShareRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr-share/create': {
      id: '/api/qr-share/create'
      path: '/api/qr-share/create'
      fullPath: '/api/qr-share/create'
      preLoaderRoute: typeof ApiQrShareCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition/search': {
      id: '/api/nutrition/search'
      path: '/api/nutrition/search'
      fullPath: '/api/nutrition/search'
      preLoaderRoute: typeof ApiNutritionSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nutrition/generate-plan': {
      id: '/api/nutrition/generate-plan'
      path: '/api/nutrition/generate-plan'
      fullPath: '/api/nutrition/generate-plan'
      preLoaderRoute: typeof ApiNutritionGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_doctor/doctor/scan-qr': {
      id: '/_doctor/doctor/scan-qr'
      path: '/scan-qr'
      fullPath: '/doctor/scan-qr'
      preLoaderRoute: typeof DoctorDoctorScanQrRouteImport
      parentRoute: typeof DoctorDoctorRoute
    }
    '/_doctor/doctor/profile': {
      id: '/_doctor/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorDoctorProfileRouteImport
      parentRoute: typeof DoctorDoctorRoute
    }
    '/_doctor/doctor/appointments': {
      id: '/_doctor/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorDoctorAppointmentsRouteImport
      parentRoute: typeof DoctorDoctorRoute
    }
    '/_admin/admin/patients': {
      id: '/_admin/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminAdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/doctors': {
      id: '/_admin/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminAdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_doctor/doctor/patient/$id': {
      id: '/_doctor/doctor/patient/$id'
      path: '/patient/$id'
      fullPath: '/doctor/patient/$id'
      preLoaderRoute: typeof DoctorDoctorPatientIdRouteImport
      parentRoute: typeof DoctorDoctorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDoctorsRoute: typeof AdminAdminDoctorsRoute
  AdminAdminPatientsRoute: typeof AdminAdminPatientsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDoctorsRoute: AdminAdminDoctorsRoute,
  AdminAdminPatientsRoute: AdminAdminPatientsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorDoctorRouteChildren {
  DoctorDoctorAppointmentsRoute: typeof DoctorDoctorAppointmentsRoute
  DoctorDoctorProfileRoute: typeof DoctorDoctorProfileRoute
  DoctorDoctorScanQrRoute: typeof DoctorDoctorScanQrRoute
  DoctorDoctorPatientIdRoute: typeof DoctorDoctorPatientIdRoute
}

const DoctorDoctorRouteChildren: DoctorDoctorRouteChildren = {
  DoctorDoctorAppointmentsRoute: DoctorDoctorAppointmentsRoute,
  DoctorDoctorProfileRoute: DoctorDoctorProfileRoute,
  DoctorDoctorScanQrRoute: DoctorDoctorScanQrRoute,
  DoctorDoctorPatientIdRoute: DoctorDoctorPatientIdRoute,
}

const DoctorDoctorRouteWithChildren = DoctorDoctorRoute._addFileChildren(
  DoctorDoctorRouteChildren,
)

interface DoctorRouteChildren {
  DoctorDoctorRoute: typeof DoctorDoctorRouteWithChildren
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorDoctorRoute: DoctorDoctorRouteWithChildren,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientAaraRoute: typeof PatientAaraRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientCarePlanRoute: typeof PatientCarePlanRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientDrugSafetyRoute: typeof PatientDrugSafetyRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientShareRoute: typeof PatientShareRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAaraRoute: PatientAaraRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientCarePlanRoute: PatientCarePlanRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientDrugSafetyRoute: PatientDrugSafetyRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientShareRoute: PatientShareRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAnalyzeReportRoute: ApiAnalyzeReportRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDrugInteractionRoute: ApiDrugInteractionRoute,
  ApiMedAnalysisRoute: ApiMedAnalysisRoute,
  ApiVapiCallRoute: ApiVapiCallRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiNutritionGeneratePlanRoute: ApiNutritionGeneratePlanRoute,
  ApiNutritionSearchRoute: ApiNutritionSearchRoute,
  ApiQrShareCreateRoute: ApiQrShareCreateRoute,
  ApiQrShareRevokeRoute: ApiQrShareRevokeRoute,
  ApiQrShareViewRoute: ApiQrShareViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
